/*
 * File: app/view/pnlReserva.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.pnlReserva', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlreserva',

    requires: [
        'reservas_puce.view.pnlReservaViewModel',
        'reservas_puce.view.pnlReservaViewController',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Check',
        'Ext.toolbar.Paging'
    ],

    controller: 'pnlreserva',
    viewModel: {
        type: 'pnlreserva'
    },
    layout: 'fit',
    title: 'Reservas',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'datefield',
                    id: 'txtFechaBuscar',
                    fieldLabel: 'Fecha',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'textfield',
                    id: 'txtUsuarioBuscar',
                    fieldLabel: 'Usuario',
                    name: 'usuario'
                },
                {
                    xtype: 'textfield',
                    id: 'txtCedulaBuscar',
                    fieldLabel: 'Cédula',
                    name: 'cedula'
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    id: 'cbLugar',
                    fieldLabel: 'Lugar',
                    name: 'id_lugar',
                    editable: false,
                    displayField: 'descripcion',
                    queryMode: 'local',
                    store: 'Lugar',
                    valueField: 'id',
                    listeners: {
                        select: 'onCbLugarSelect'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'cbHorario',
                    fieldLabel: 'Horario',
                    name: 'id_horario',
                    editable: false,
                    displayField: 'hora_inicio',
                    queryMode: 'local',
                    store: 'Horario',
                    valueField: 'id',
                    listeners: {
                        focus: 'onCbHorarioFocus'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btNBuscar',
                    text: 'Buscar Reservas',
                    listeners: {
                        click: 'onBtNBuscarClick'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnReservaNuevo',
                    text: 'Nuevo',
                    listeners: {
                        click: 'onBtnReservaNuevoClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnReservaEliminar',
                    text: 'Eliminar',
                    listeners: {
                        click: 'onBtnReservaEliminarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'grdReserva',
            title: '',
            forceFit: true,
            store: 'Reserva',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'usuario',
                    text: 'Usuario'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombre',
                    text: 'Nombre'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'cedula',
                    text: 'Cedula'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lugar',
                    text: 'Lugar'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'fecha_reserva',
                    text: 'Fecha',
                    format: 'd-m-Y'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'hora_inicio',
                    text: 'Hora de inicio',
                    format: 'H:i'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'hora_fin',
                    text: 'Hora de fin',
                    format: 'H:i'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_horario',
                    text: 'Horario'
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'asistencia',
                    text: 'Asistencia',
                    listeners: {
                        checkchange: 'onCheckcolumnCheckChange'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'Reserva'
                }
            ]
        }
    ]

});