/*
 * File: app/view/vwprtLogin.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.vwprtLogin', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.vwprtlogin',

    requires: [
        'reservas_puce.view.vwprtLoginViewModel',
        'reservas_puce.view.vwprtLoginViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden'
    ],

    controller: 'vwprtlogin',
    viewModel: {
        type: 'vwprtlogin'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            layout: 'center',
            bodyStyle: 'background-color:#666666',
            items: [
                {
                    xtype: 'panel',
                    height: 250,
                    width: 600,
                    layout: 'border',
                    title: '',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'west',
                            width: 207,
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            }
                        },
                        {
                            xtype: 'form',
                            region: 'center',
                            id: 'FormaLogin',
                            bodyPadding: 10,
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '20 20 20 20',
                                    fieldLabel: 'Usuario',
                                    name: 'usuario'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 20 20 20',
                                    fieldLabel: 'Contraseña',
                                    name: 'clave',
                                    inputType: 'password',
                                    listeners: {
                                        specialkey: 'onTextfieldSpecialkey'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 20 20',
                                    text: 'Aceptar',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    value: 'Desarrollado por la Dirección Informática de la PUCE',
                                    fieldStyle: 'fontFamily : Georgia; font-style: italic; font-size: 14px'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: 'Aplicacion',
                                    name: 'aplicacion',
                                    value: 'reservas_puce'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});