/*
 * File: app/view/wndNuevoUsuario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.wndNuevoUsuario', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndnuevousuario',

    requires: [
        'reservas_puce.view.wndNuevoUsuarioViewModel',
        'reservas_puce.view.wndNuevoUsuarioViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.FieldContainer',
        'Ext.button.Button'
    ],

    controller: 'wndnuevousuario',
    viewModel: {
        type: 'wndnuevousuario'
    },
    id: 'wndNuevoUsuario',
    width: 450,
    layout: 'fit',
    closable: false,
    title: 'Nuevo Usuario',
    modal: true,

    items: [
        {
            xtype: 'form',
            id: 'frmNuevoUsuario',
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Usuario',
                    labelWidth: 60,
                    name: 'usuario',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre',
                    labelWidth: 60,
                    name: 'nombre',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Apellido',
                    labelWidth: 60,
                    name: 'apellido',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Cédula',
                    labelWidth: 60,
                    name: 'cedula',
                    allowBlank: false
                },
                {
                    xtype: 'fieldcontainer',
                    height: 37,
                    width: 400,
                    fieldLabel: '',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnUsuarioCancelar',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnUsuarioCancelarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnUsuarioGuardar',
                            margin: '0 0 0 10',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnUsuarioGuardarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});