/*
 * File: app/view/wndNuevoUsuarioViewController1.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.wndNuevoUsuarioViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wndnuevotipo',

    onBtnTipoCancelarClick: function(button, e, eOpts) {
        Ext.getCmp('wndNuevoTipo').close();
    },

    onBtnTipoGuardarClick: function(button, e, eOpts) {
        var form = Ext.getCmp('frmNuevoTipo').getForm(),
            store = Ext.getStore('Tipo');
        if (form.isValid()) {
            Ext.Ajax.request({
                url: '../servidor/reservas_puce/tipo/verificar',
                method:"post",
                params: {
                    descripcion: Ext.getCmp('txtNuevoTipoDescripcion').getValue()
                },
                success: function( result, request ) {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success)
                    {
                        var values = form.getValues();
                        store.add(values);
                        store.sync(
                        {
                            success: function(batch, options)
                            {
                                Ext.getCmp('wndNuevoTipo').close();
                                store.load();
                                Ext.Msg.alert('Datos Guardados','Se han guardado los datos exitosamente');
                            },
                            failure: function(batch, options)
                            {

                                Ext.Msg.alert('Advertencia', 'Hubo un error.');
                                store.load();
                            }
                        }
                        );
                    }
                    else
                    {
                        Ext.Msg.alert('Alerta','Este tipo ya está ingresado.');
                    }
                },

                failure: function(response, opts) {
                    Ext.Msg.alert('Alerta','Este tipo ya está ingresado.');

                }
            });
        }
        else
        {
            Ext.Msg.alert('Error','Ingrese los datos correctamente');
        }

    }

});
