/*
 * File: app/view/pnlHorario.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.pnlHorario', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pnlhorario',

    requires: [
        'reservas_puce.view.pnlHorarioViewModel',
        'reservas_puce.view.pnlHorarioViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.field.Time',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'pnlhorario',
    viewModel: {
        type: 'pnlhorario'
    },
    layout: 'fit',
    title: 'Horario',

    items: [
        {
            xtype: 'gridpanel',
            id: 'grdHorario',
            title: '',
            forceFit: true,
            store: 'Lugar',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'descripcion',
                    text: 'Descripcion'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'id_estado',
                    text: 'Estado'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'aforo',
                    text: 'Aforo',
                    format: '0,000'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'id_tipo',
                    text: 'Tipo'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'id_lugar',
                    text: 'Lugar'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'nivel',
                    text: 'Nivel',
                    format: '0,000'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'hora_inicio',
                    text: 'Hora Inicio',
                    format: 'H:i',
                    editor: {
                        xtype: 'timefield',
                        name: 'hora_inicio',
                        allowBlank: false,
                        format: 'H:i'
                    }
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'hora_fin',
                    text: 'Hora Fin',
                    format: 'H:i',
                    editor: {
                        xtype: 'timefield',
                        name: 'hora_fin',
                        allowBlank: false,
                        format: 'H:i'
                    }
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'intervalo',
                    text: 'Intervalo',
                    format: 'H:i',
                    editor: {
                        xtype: 'timefield',
                        name: 'intervalo',
                        allowBlank: false,
                        format: 'H:i'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    listeners: {
                        edit: 'onRowEditingEdit'
                    }
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnHorarioNuevo',
                    text: 'Nuevo',
                    listeners: {
                        click: 'onBtnHorarioNuevoClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnHorarioEliminar',
                    text: 'Eliminar',
                    listeners: {
                        click: 'onBtnHorarioEliminarClick'
                    }
                }
            ]
        }
    ]

});