/*
 * File: app/model/Lugar_Model.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.model.Lugar_Model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'float',
            name: 'id'
        },
        {
            type: 'string',
            name: 'descripcion'
        },
        {
            type: 'float',
            name: 'id_estado'
        },
        {
            type: 'float',
            name: 'aforo'
        },
        {
            type: 'float',
            name: 'id_tipo'
        },
        {
            type: 'float',
            name: 'id_lugar'
        },
        {
            type: 'float',
            name: 'nivel'
        },
        {
            type: 'date',
            name: 'hora_inicio',
            dateFormat: 'H:i'
        },
        {
            type: 'date',
            name: 'hora_fin',
            dateFormat: 'H:i'
        },
        {
            type: 'date',
            name: 'intervalo',
            dateFormat: 'H:i'
        }
    ]
});