/*
 * File: app/view/pnlNuevaReservaViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('reservas_puce.view.pnlNuevaReservaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pnlnuevareserva',

    onBtnNuevaReservaEntrarClick: function(button, e, eOpts) {

        var g = Ext.getCmp('grdNuevaReservaLugar');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;

        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un lugar');
        else
        {
            var rec = g.selection;
            Ext.Ajax.request({
                url: '../servidor/reservas_puce/lugar/verificar_ingreso',
                method:"post",

                params:{
                    id_lugar: rec.data.id
                },

                success: function(result, success)
                {
                    var responseData = Ext.JSON.decode(result.responseText);
                    if(responseData.success)
                    {

                        var storeLugar = Ext.getStore('Lugar');
                        storeLugar.removeAll();
                        storeLugar.proxy.extraParams = {
                            busqueda: 3,
                            id_lugar: rec.data.id
                        };
                        storeLugar.load();

                        var storeHorario = Ext.getStore('Horario');
                        storeHorario.removeAll();

                    }
                    else
                    {
                        Ext.Msg.alert('Alerta', 'No existen más lugares.');
                    }
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });
        }


    },

    onBtnNuevaReservaRegresarClick: function(button, e, eOpts) {
        var storeHorario = Ext.getStore('Horario');
        storeHorario.removeAll();
        var storeLugar = Ext.getStore('Lugar');
        var records = storeLugar.getData().items;
        Ext.Ajax.request({
            url: '../servidor/reservas_puce/lugar/verificar_regreso',
            method:"post",

            params:{
                id_lugar: records[0].data.id_lugar
            },

            success: function(result, success)
            {
                var responseData = Ext.JSON.decode(result.responseText);
                if(responseData.success)
                {
                    storeLugar.proxy.extraParams = {
                        busqueda: 4,
                        id_lugar: records[0].data.id_lugar
                    };
                    storeLugar.removeAll();
                storeLugar.load();}
                else
                {
                    Ext.Msg.alert('Alerta', 'No existen más lugares.');
                }
            },

            failure: function(batch, success)
            {
                Ext.Msg.alert('Error', 'Hubor un error');
            }
        });
    },

    onGrdNuevaReservaLugarCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(Ext.getCmp('txtNuevaReservaFecha').getValue()!== null && Ext.getCmp('txtUsuarioReserva').getValue()!== '' && Ext.getCmp('txtCedulaReserva').getValue() !== '' && Ext.getCmp('txtNombreReserva').getValue() !== ''){
            var lugar = record.data.id;
            var store = Ext.getStore('Horario');
            store.removeAll();
            store.proxy.extraParams = {
                id: lugar,
                fecha: Ext.getCmp('txtNuevaReservaFecha').getValue()
            };
            store.load();
        }
        else{
            Ext.Msg.alert('Alerta','Debe llenar los parámetros antes de continuar con el proceso');
        }
    },

    onBtnNuevaReservaCancelarClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlReservaUsuario'))
        {
            ME.getView().down('#pnlCentral').removeAll();
            var panel = Ext.create('reservas_puce.view.pnlReserva');
            var store = Ext.getStore('Reserva');
            store.removeAll();
            ME.getView().down('#pnlCentral').add(panel);

        }
    },

    onBtnNuevaReservaGuardarClick: function(button, e, eOpts) {
        var lugar = Ext.getCmp('grdNuevaReservaLugar');
        var lugar_arrayKeys = lugar.getSelectionModel().selected.items;
        var lugar_indice = lugar.getSelectionModel().selectionStartIdx;

        if(lugar_arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un lugar');
        else
        {
            var horario = Ext.getCmp('grdNuevaReservaHorario');
            var horario_arrayKeys = horario.getSelectionModel().selected.items;
            var horario_indice = horario.getSelectionModel().selectionStartIdx;

            if(horario_arrayKeys.length === 0)
            Ext.Msg.alert('Error', 'Debe escoger un horario');
            else
            {
                if(Ext.getCmp('txtNuevaReservaFecha').getValue() === null || Ext.getCmp('txtUsuarioReserva').getValue() === '' || Ext.getCmp('txtCedulaReserva').getValue() === '' || Ext.getCmp('txtNombreReserva').getValue() === ''){
                    Ext.Msg.alert('Error', 'Debe llenar todos los parámetros');
                }
                else{
                    var lugar_rec = lugar.selection;
                    var horario_rec = horario.selection;
                    Ext.Ajax.request({
                        url: '../servidor/reservas_puce/reserva/verificar_aforo',
                        method:"post",

                        params:{
                            lugar:lugar_rec.data.id,
                            horario:horario_rec.data.id,
                            fecha:Ext.getCmp('txtNuevaReservaFecha').getValue()
                        },

                        success: function(result, success)
                        {
                            var responseData = Ext.JSON.decode(result.responseText);
                            if(responseData.success)
                            {

                                Ext.Ajax.request({
                                    url: '../servidor/reservas_puce/reserva/verificar_reserva',
                                    method:"post",

                                    params:{
                                        fecha:Ext.getCmp('txtNuevaReservaFecha').getValue(),
                                        usuario: Ext.getCmp('txtUsuarioReserva').getValue(),
                                        bandera: 1
                                    },

                                    success: function(result, success)
                                    {
                                        var responseData = Ext.JSON.decode(result.responseText);

                                        if(responseData.success)
                                        {
                                            Ext.Ajax.request({
                                                url: '../servidor/reservas_puce/reserva/create',
                                                method:"post",

                                                params:{
                                                    lugar:lugar_rec.data.id,
                                                    horario:horario_rec.data.id,
                                                    fecha:Ext.getCmp('txtNuevaReservaFecha').getValue(),
                                                    usuario: Ext.getCmp('txtUsuarioReserva').getValue(),
                                                    nombre:Ext.getCmp('txtNombreReserva').getValue(),
                                                    cedula: Ext.getCmp('txtCedulaReserva').getValue(),
                                                    bandera: 1
                                                },

                                                success: function(result, success)
                                                {
                                                    var responseData = Ext.JSON.decode(result.responseText);

                                                    if(responseData.success)
                                                    {

                                                        Ext.Ajax.request({
                                                            url: '../servidor/reservas_puce/reserva/correo',
                                                            method:"post",

                                                            params:{
                                                                usuario: Ext.getCmp('txtUsuarioReserva').getValue(),
                                                                reserva: responseData.data
                                                            },

                                                            success: function(batch, success)
                                                            {
                                                                if(!Ext.getCmp('pnlReserva'))
                                                                {
                                                                    ME.getView().down('#pnlCentral').removeAll();
                                                                    var panel = Ext.create('reservas_puce.view.pnlReserva');
                                                                    var storeReserva = Ext.getStore('Reserva');
                                                                    storeReserva.load();
                                                                    ME.getView().down('#pnlCentral').add(panel);
                                                                }
                                                                Ext.Msg.alert('Datos Guardados','Se han guardado los datos exitosamente');
                                                            },

                                                            failure: function(batch, success)
                                                            {
                                                                Ext.Msg.alert('Error', 'Hubor un error');
                                                            }
                                                        });
                                                    }
                                                },

                                                failure: function(batch, success)
                                                {
                                                    Ext.Msg.alert('Error', 'Hubor un error');
                                                }
                                            });
                                        }
                                        else
                                        {
                                            Ext.Msg.alert('Alerta','Ya tiene reservas este día.');
                                        }
                                    },

                                    failure: function(batch, success)
                                    {
                                        Ext.Msg.alert('Error', 'Hubor un error');
                                    }
                                });
                            }
                            else
                            {
                                Ext.Msg.alert('Alerta','Este lugar se encuentra lleno, elija otro lugar u horario.');
                            }
                        },

                        failure: function(batch, success)
                        {
                            Ext.Msg.alert('Error', 'Hubor un error');
                        }
                    });
                }
            }
        }
    }

});
